<?php
/**
 * Message translations.
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    /**
     * Авторизация
     */
    'Return to Dashboard' => 'Вернуться назад',
    'Sign In' => 'Вход',
    'Sign Up' => 'Регистрация',
    'Join Inely' => 'Присоединяйтесь к Inely',
    'A few words about you' => 'Несколько слов о Вас',
    'Username' => 'Имя пользователя',
    'Password' => 'Пароль',
    'Retype your password' => 'Повторите пароль',
    'Passwords do not match' => 'Пароли не совпадают',
    'Choose your username' => 'Введите имя пользователя',
    'Email address' => 'Введите Ваш Email',
    'Create a password' => 'Придумайте пароль',
    'Finish sign up' => 'Завершить регистрацию',
    'Remember Me' => 'Запомнить меня',
    'Password recovery' => 'Восстановление пароля',
    'Incorrect username or password.' => 'Неправильное имя пользователя или пароль',
    'Submit' => 'Отправить',
    'Welcome to Inely.' => 'Добро пожаловать в Inely.',
    'Your login information was sent to <b>{email}</b>' => 'Ваши персональные данные были отправлены на <b>{email}</b>',
    'This will be your new password' => 'Это будет вашим новым паролем',
    'Please enter a new password for your account' => 'Пожалуйста, введите новый пароль для вашего аккаунта',
    'This username has already been taken' => 'Данное имя уже кем-то занято!',
    'This email address has already been taken' => 'Данный e-mail уже кем-то занят!',
    'There is no user with such email' => 'Пользователь с таким email не зарегистрирован',
    'You\'ll love your Inely' => 'Вам понравится Inely',
    'And your new friend!' => 'И конечно же ваш новый друг!',
    'Notifications, Lists, Stats...' => 'Уведомления, списки, статистика...',
    'A new look at the task scheduling' => 'Новый взгляд на планирование задач',
    'Manage tasks from anywhere' => 'Управляйте задачами откуда угодно',
    'Please enter your e-mail. It will receive a letter with instructions to reset your password.' => 'Пожалуйста, укажите Ваш e-mail. На него придет письмо с инструкциями по восстановлению пароля.',
    'Email confirmation' => 'Подтверждение электронного адреса',
    'Check your email for further instructions' => 'Проверьте вашу почту',
    'New password was saved' => 'Новый пароль был сохранен',
    'Password recover' => 'Восстановление пароля',
    'No confirmation code' => 'Отсутствует код подтверждения',
    'Invalid token. Maybe you have already confirmed your account?' => 'Неверный токен. Может быть вы уже подтвердили свой аккаунт?',
    'Sorry, we are unable to reset password for email provided' => 'Извините, мы не можем сбросить пароль для этого e-mail',
    'Sorry, an error occurred with confirmation' => 'Извините, произошла ошибка подтверждения e-mail',
    'Thanks! Account e-mail address confirmed successfully' => 'Спасибо! Ваш e-mail успешно подтверждён',
    'Yes' => 'Да',
    'No' => 'Нет',
    'You forgot?' => 'Забыли?',
    'Send' => 'Отправить',
    /**
     * Выбор персонажа
     */
    'Finish' => 'Завершить',
    'Coming Soon...' => 'Скоро...',
    'Befriend!' => 'Дружить!',
    'Are you sure?' => 'Вы уверены?',
    'Your character has been uploaded!' => 'Ваш персонаж был загружен!',
    'No more files!' => 'Возможна загрузка только одного файла!',
    'Try something interesting!' => 'Попробуй кое-что интересное!',
    'In addition to the default characters you can download own. What could be better?' => 'Помимо проработанных персонажей ты можешь загрузить и собственного. Что может быть лучше?',
    'Unfortunately, in this version some features might become unstable. <a href="#" id="start">I\'ve Changed My Mind</a>' => 'К сожалению, в этой версии некоторые функции могут работать нестабильно. <a href="#" id="start">Я передумал.</a>',
    'Hi! Nice to see you here.' => 'Привет! Очень приятно видеть тебя здесь.',
    'Robo was designed to be a friendly robot. He likes to achieve goals, play games, and helping people.' => 'Robo был разработан чтобы быть дружелюбным помощником. Он любит достигать своих целей, играть в игры и помогать людям.',
    'EVE is one of several robots who are sent to Earth. She likes to fly and likes draw. After meeting you, she making a top priority to protect you.' => 'Eve - один из нескольких роботов посланных на Землю. Умеет летать и любит рисовать. После встречи с тобой, она делает своим главным приоритетом защищать тебя.',
    'My name is Robo. I\'m glad that you decided to visit Inely, and I would be happy to help you get started. I hope you will enjoy it!' => 'Меня зовут Robo. Я рад, что ты решил посетить Inely и я с удовольствием помогу тебе здесь освоиться.',
    'Please, choose someone who you like and we will continue. Be a little bit responsible :) <a href="#" id="own">Maybe you want own character?</a>' => 'Выбери того, кто тебе по душе и мы продолжим. Будь немножко ответственным :) <a href="#" id="own">Или ты хочешь своего персонажа?</a>',
    'Holo the wise wolf in human form with cute ears and tail. She is very charming and... wise.' => 'Холо мудрый волк в человеческом обличии с хвостом и ушками. Очень очаровательная и... мудрая.',
    'For the best view we recommend PNG format!' => 'Для наилучшего вида рекомендуется png формат!',
    'Enter the name of your character' => 'Как зовут Вашего персонажа?',
    /**
     * Время
     */
    'today' => 'сегодня',
    '{delta, plural, =1{a day} other{in # days}}' => '{delta, plural, =1{завтра} one{через # день} few{через # дня} many{через # дней} other{через # дня}}',
    '{delta, plural, =1{yesterday} other{in # days}} ago' => '{delta, plural, =1{вчера} one{# день назад} few{# дня назад} many{# дней назад} other{# дня назад}}',
    /**
     * Задачи
     */
    'Inbox' => 'Входящие',
    'Projects' => 'Проекты',
    'Today' => 'Сегодня',
    '9' => '12',
    'Completed' => 'Завершенные',
    'Add Task' => 'Добавить задачу',
    'Next 7 days' => 'След. 7 дней',
    'Sort by priority' => 'Сортировать по приоритету',
    'Sort by name' => 'Сортировать по названию',
    'Sort by date' => 'Сортировать по дате',
    'Export as a template' => 'Экспорт в качестве шаблона',
    'Import from template' => 'Импорт из шаблона',
    'Delete completed tasks' => 'Удалить завершенные задачи',
    /**
     * Помощь
     */
    'General' => 'Основная информация',
    'Dates and times' => 'Дата и время',
    'Keywords' => 'Ключевые слова',
    'Keyboard shortcuts' => 'Горячие клавиши',
    'Notes' => 'Заметки и комментарии',
];
