<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    /**
     * Authentication
     */
    'Return to Dashboard' => 'Вернуться назад',
    'Sign In' => 'Вход',
    'Sign Up' => 'Регистрация',
    'Join Inely' => 'Присоединяйтесь к Inely',
    'A few words about you' => 'Несколько слов о Вас',
    'Username' => 'Имя пользователя',
    'Password' => 'Пароль',
    'Choose your username' => 'Введите имя пользователя',
    'Email address' => 'Введите Ваш Email',
    'Create a password' => 'Придумайте пароль',
    'Finish sign up' => 'Завершить регистрацию',
    'Remember Me' => 'Запомнить меня',
    'Password recovery' => 'Восстановление пароля',
    'There is no user with such email' => 'Пользователь с таким email не зарегистрирован',
    'you forgot?' => 'забыли?',
    'You\'ll love Inely' => 'Вы полюбите Inely',
    'Achievements do not let you get bored' => 'Достижения не дадут вам заскучать',
    'Watch your performance' => 'Наблюдайте за своей производительностью',
    'Manage tasks from anywhere' => 'Управляйте задачами откуда угодно',
    'Please enter your e-mail. It will receive a letter with instructions to reset your password.' => 'Пожалуйста, укажите Ваш e-mail. На него придет письмо с инструкциями по восстановлению пароля.',
    'YES' => 'Да',
    'NO' => 'Нет',
    'Send' => 'Отправить',

    /**
     *
     */
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',

];
