<?php

/**
 * Message translations.
 *
 * @author rootkit
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [

    /**
     * Header
     */
    'Home' => 'Начало',
    'Intro' => 'Введение',
    'Description' => 'Описание',
    'Features' => 'Особенности',
    'Review' => 'Обзор',
    'Go Now' => 'Начните сейчас!',

    /**
     * Title
     */
    'Inely. Your personal assistant.' => 'Inely. Ваш личный помощник.',

    /**
     * Revolution Slider
     */
    'Welcome to Inely' => 'Добро пожаловать',
    'Welcome!' => 'Добро пожаловать!',
    'He is here to help!' => 'Он уже готов помочь!',
    'Personal Assistant ready to make your life more manageable. In today\'s world it is easy to feel like there is never enough time in a day to get it all done. That is where My Personal Assistant can come in.' =>
        'Личный помощник готов сделать Вашу жизнь чуточку гибче. В современном мире легко ощутить нехватку времени в сутках, чтобы успеть аболютно всё. И  здесь на помощь приходит Inely.',


    /**
     * Intro Section
     */
    'Welcome to Inely.<br>Your scheduler.' => 'Встречайте Inely.<br>Ваш планировщик.',
    'Manage your personal goals, and your team’s projects in one place. Inely designed to adapt to all needs.' => 'Отслеживайте личные задачи, планируйте рабочие проекты, и всё остальное в одном месте. Inely подходит для любой цели.',
    'images/services/main-fbrowser.png' => 'images/services/ru/main-fbrowser.png',

    /**
     * Review Section
     */
    '' => '',

    /**
     * Features Section
     */
    'Features Overview' => 'Обзор возможностей',
    'Some of the Features that are gonna blow your mind off' => 'Несколько особенностей, которые сведут Вас с ума',

    'Responsive Layout' => 'Адаптивность',
    'Powerful Layout with Responsive functionality that can be adapted to any screen size. Resize browser to view.' => 'Мощная разметка с отзывчивой функциональностью может быть адаптирована к любому размеру экрана.',

    'Retina Graphics' => 'Retina графика',
    'Looks beautiful &amp; ultra-sharp on Retina Screen Displays. Retina Icons &amp; all others graphics are optimized.' => 'Превосходный вид на мониторах с высоким разрешением. Retina иконки &amp; прочая графика оптимизирована.',

    'Powerful Performance' => 'Производительность',
    'Inely includes tons of optimized code that are completely customizable and deliver unmatched optimization.' => 'Inely включает в себя тонны оптимизированного кода, с непревзойденной оптимизацией.',

    'Personalization' => 'Персонализация',
    'You have complete easy control on each &amp; every element that provides endless customization possibilities.' => 'Вы полностью контролируете каждый элемент на Вашей доске, что обеспечивает огромные возможности.',

    'Visualize opportunities' => 'Визуализация',
    'By means of adaptive schedules trace the productivity and over time visualize it.' => 'С помощью адаптивных графиков отслеживайте свою производительность и со временем визуализируйте её.',

    'Fascinating achievements' => 'Увлекательность',
    'Earn achievements, increasing the level, receiving more coins and getting to various stages of the game.' => 'Зарабатывайте достижения, повышая свой уровень, получая больше монет и попадая в различные этапы игры.',

    /**
     * Code Section
     */
    'Hours of Coding' => 'Часов за кодом',
    'Lines of Code' => 'Строчек кода',
    'Cups of Tea' => 'Чашек чая',
    'Commits in Git' => 'Коммитов в Git',
    'images/services/home-testi-bg.jpg' => 'images/services/ru/home-testi-bg.jpg',

    /**
     * Retina Section
     */
    'We know you want it!' => 'Мы знаем, что Вам нужно',
    'Created with special passion &amp; and intuitivism. You shouldn\'t study it long.' => 'Создан быть интуитивно понятным. Вам не придётся долго его изучать.',
    'images/services/fbrowser2.png' => 'images/services/ru/fbrowser2.png',

    /**
     * Go Now Section
     */
    'Now that you have read all the Tid-Bits, <strong>Let\'s Go!</strong>' => 'Теперь, когда вы узнали о всех лакомых кусочках, <strong>начнём!</strong>',

    /**
     * Footer
     */
    'Crafted with love by rootkit.' => 'Созданный с любовью от rootkit.',
    'Coins earned' => 'Заработано монет',
    'Tasks performed' => 'Выполнено задач',
    'Client Testimonials' => 'Отзывы пользователей',
    'Send Message' => 'Отправить письмо',
    'Message Sent Successfully!' => 'Ваше сообщение отправлено!',
    'Full Name' => 'Ваше имя...',
    'Email Address' => 'Email...',
    'Message' => 'Ваше сообщение...',
    'Send Letter' => 'Отправить письмо',

    /**
     * Errors
     */
    'Ooopps.! The Page you were looking for, couldn\'t be found.' => 'Упс! К сожалению, страница, которую вы запросили, не существует.',
    'Try to search in other <a href="/">place</a>.' => 'Попробуйте поискать её <a href="/">в другом месте.</a>',
    'Something went wrong. We apologize.' => 'Что-то пошло не так. Приносим свои извинения.',

    /**
     * The shift to the left for the header on slider
     */
    '130' => '125',
    '485' => '468',
    '460' => '438',
    '380' => '360'
];
