<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    'Hi, {username}!' => 'Привет, {username}!',
    'Welcome to Inely - User account activation' => 'Добро пожаловать в Inely - Активация аккаунта',
    'Your user account with the e-mail address {email} has been created.' => 'Твоя учетная запись с адресом {email} была успешно создана.',
    'Please follow the link below to activate your account. The link will remain valid for 15 days.' => 'Перейди по ссылке ниже, чтобы активировать аккаунт. Ссылка будет действительна в течение 15 дней.',
    'Thank you for choosing Inely as your personal task manager.' => 'Спасибо за то, что выбрал Inely в качестве своего персонального планировщика.',
    'Link this email address' => 'Подтвердить этот e-mail',
    'Someone recently requested a password change for your Inely account. If this was you, you can set a new password by click on link below.' => 'Кто-то недавно запросил изменение пароля для вашей учетной записи на Inely. Если это были вы, вы можете установить новый пароль, нажав на ссылку ниже.',
    'If you don\'t want to change your password or didn\'t request this, just ignore and delete this message.' => 'Если вы не хотите менять свой пароль или не запрашивали его изменение, просто игнорируйте или удалите это письмо.',
    'Reset password' => 'Сбросить пароль',
    'Inely password reset' => 'Сброс пароля для Inely'

];
